services:
  database:
    image: mysql:5.7
    restart: always
    volumes:
      - ./DATABASE:/docker-entrypoint-initdb.d
    
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: "database"  
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_PASSWORD: '123'
      MYSQL_DATABASE: 'drs_baza'
      MYSQL_CURSORCLASS: 'DictCursor'

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '123'

  engine:
   build: ./ENGINE
   ports:
     - "5001:5001"
   links: 
     - database
   depends_on:
     - database

volumes:
  database:
  engine:

#
#ui:
#  build: ./UI
#  ports:
#    - "3000:3000"
#  volumes:
#    - ./UI:/main
#  depends_on:
#    - engine
      